# Generated by Django 5.2.3 on 2026-06-06 19:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Blood group required', max_length=5)),
                ('patient_name', models.CharField(help_text='Name of the patient', max_length=255)),
                ('age', models.PositiveIntegerField(help_text='Age of the patient')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Gender of the patient', max_length=20)),
                ('hospital_name', models.CharField(help_text='Hospital name', max_length=255)),
                ('hospital_address', models.TextField(help_text='Full hospital address')),
                ('hospital_lat', models.DecimalField(blank=True, decimal_places=6, help_text='Hospital latitude', max_digits=9, null=True)),
                ('hospital_lng', models.DecimalField(blank=True, decimal_places=6, help_text='Hospital longitude', max_digits=9, null=True)),
                ('contact_phone', models.CharField(help_text='Emergency contact number', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('units_needed', models.PositiveIntegerField(default=1, help_text='Number of blood units required')),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='active', help_text='Current status of the SOS request', max_length=20)),
                ('responders_count', models.PositiveIntegerField(default=0, help_text='Number of people who have responded')),
                ('resolution_note', models.TextField(blank=True, help_text='Note about how the request was resolved', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the request was resolved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(help_text='User who created this SOS request', on_delete=django.db.models.deletion.CASCADE, related_name='sos_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SOS Request',
                'verbose_name_plural': 'SOS Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SOSResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_help', models.BooleanField(default=True, help_text='Whether the responder can help')),
                ('estimated_arrival_minutes', models.PositiveIntegerField(blank=True, help_text='Estimated time to reach hospital in minutes', null=True)),
                ('note', models.TextField(blank=True, help_text='Additional note from responder', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responder', models.ForeignKey(help_text='User responding to the SOS', on_delete=django.db.models.deletion.CASCADE, related_name='sos_responses', to=settings.AUTH_USER_MODEL)),
                ('sos_request', models.ForeignKey(help_text='The SOS request being responded to', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='sos.sosrequest')),
            ],
            options={
                'verbose_name': 'SOS Response',
                'verbose_name_plural': 'SOS Responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sosrequest',
            index=models.Index(fields=['blood_type'], name='sos_sosrequ_blood_t_926fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='sosrequest',
            index=models.Index(fields=['status'], name='sos_sosrequ_status_5dd5b8_idx'),
        ),
        migrations.AddIndex(
            model_name='sosrequest',
            index=models.Index(fields=['hospital_lat', 'hospital_lng'], name='sos_sosrequ_hospita_c697b6_idx'),
        ),
        migrations.AddIndex(
            model_name='sosrequest',
            index=models.Index(fields=['-created_at'], name='sos_sosrequ_created_25c8ec_idx'),
        ),
        migrations.AddIndex(
            model_name='sosresponse',
            index=models.Index(fields=['sos_request', 'responder'], name='sos_sosresp_sos_req_894f9d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sosresponse',
            unique_together={('sos_request', 'responder')},
        ),
    ]
