# Generated by Django 5.2.3 on 2026-06-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosrequest',
            name='hospital_lat',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Hospital latitude', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sosrequest',
            name='hospital_lng',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Hospital longitude', max_digits=10, null=True),
        ),
    ]
