# Generated by Django 5.2.3 on 2026-07-04 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0002_add_sos_response_status'),
        ('sos', '0002_alter_sosrequest_hospital_lat_and_more'),
    ]

    operations = [
    ]
