# Generated by Django 5.2.3 on 2026-07-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0003_merge_20260704_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosresponse',
            name='arrived_at',
            field=models.DateTimeField(blank=True, help_text='When donor arrived at hospital', null=True),
        ),
        migrations.AddField(
            model_name='sosresponse',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When donor cancelled their response', null=True),
        ),
        migrations.AddField(
            model_name='sosresponse',
            name='departed_at',
            field=models.DateTimeField(blank=True, help_text='When donor departed for hospital', null=True),
        ),
        migrations.AlterField(
            model_name='sosrequest',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('awaiting_arrival', 'Awaiting Donor Arrival'), ('in_progress', 'Donation In Progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled'), ('expired', 'Expired - No Responses')], default='active', help_text='Current status of the SOS request', max_length=20),
        ),
        migrations.AlterField(
            model_name='sosresponse',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending - Awaiting Patient Review'), ('accepted', 'Accepted by Patient'), ('rejected', 'Rejected by Patient'), ('in_transit', 'Donor is On the Way'), ('arrived', 'Donor Arrived at Hospital'), ('donating', 'Donation In Progress'), ('donated', 'Donation Completed'), ('no_show', 'Donor Did Not Arrive'), ('cancelled', 'Cancelled by Donor')], default='pending', help_text='Status of the donor response', max_length=20),
        ),
    ]
