# Generated by Django 5.2.3 on 2026-07-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0004_sosresponse_arrived_at_sosresponse_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosrequest',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Age of the patient (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='sosrequest',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Gender of the patient (optional)', max_length=20, null=True),
        ),
    ]
