# Generated by Django 5.2.3 on 2026-06-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative')], help_text='Blood group code (e.g., O+, A-)', max_length=5, unique=True)),
                ('name', models.CharField(help_text='Full name of blood group (e.g., O Positive)', max_length=20)),
                ('compatibility', models.JSONField(default=list, help_text='List of compatible blood types for donation')),
                ('sort_order', models.IntegerField(default=0, help_text='Order for displaying blood types')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this blood type is active')),
            ],
            options={
                'verbose_name': 'Blood Type',
                'verbose_name_plural': 'Blood Types',
                'ordering': ['sort_order', 'code'],
                'indexes': [models.Index(fields=['code'], name='blood_types_code_064125_idx'), models.Index(fields=['is_active'], name='blood_types_is_acti_6aa047_idx')],
            },
        ),
    ]
