# Generated by Django 5.2.3 on 2026-06-21 09:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(help_text='The question text')),
                ('answer', models.TextField(help_text='The answer text')),
                ('category', models.CharField(help_text='Category for better matching (e.g., eligibility, safety, process)', max_length=100)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords for better matching')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority FAQs are matched first')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this FAQ is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['-priority', 'category'],
                'indexes': [models.Index(fields=['category'], name='assistant_f_categor_440ca7_idx'), models.Index(fields=['is_active'], name='assistant_f_is_acti_2f774e_idx'), models.Index(fields=['-priority'], name='assistant_f_priorit_4aec56_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(blank=True, help_text='Session ID for grouping conversations', null=True)),
                ('user_question', models.TextField(help_text="The user's question")),
                ('bot_answer', models.TextField(help_text="The bot's answer")),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence score of the match (0-1)', null=True)),
                ('category', models.CharField(blank=True, help_text='Category of the matched answer', max_length=100)),
                ('user_satisfied', models.BooleanField(blank=True, help_text='Whether user was satisfied (feedback)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_faq', models.ForeignKey(blank=True, help_text='The FAQ that was matched (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_entries', to='assistant.faq')),
            ],
            options={
                'verbose_name': 'Chat History',
                'verbose_name_plural': 'Chat Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_helpful', models.BooleanField(help_text='Whether the response was helpful')),
                ('comment', models.TextField(blank=True, help_text='Additional user comments')),
                ('suggested_answer', models.TextField(blank=True, help_text="User's suggested better answer")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_history', models.ForeignKey(help_text='The chat entry this feedback is for', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='assistant.chathistory')),
            ],
            options={
                'verbose_name': 'User Feedback',
                'verbose_name_plural': 'User Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['session_id'], name='assistant_c_session_fb7b37_idx'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['-created_at'], name='assistant_c_created_318ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['confidence_score'], name='assistant_c_confide_1cc5c7_idx'),
        ),
    ]
