# Generated by Django 5.2.3 on 2026-06-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='category',
            field=models.CharField(blank=True, help_text='Category of the matched answer', max_length=100, null=True),
        ),
    ]
