# Generated by Django 5.2.3 on 2026-06-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_alter_chathistory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='target_role',
            field=models.CharField(choices=[('both', 'Both Donor and Patient'), ('donor', 'Donor Only'), ('patient', 'Patient Only')], default='both', help_text='Target audience for this FAQ', max_length=20),
        ),
    ]
