# Generated by Django 5.2.3 on 2026-06-11 19:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood_requests', '0012_remove_donorresponse_donated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the conversation is active')),
                ('blocked_at', models.DateTimeField(blank=True, help_text='When the conversation was blocked', null=True)),
                ('block_reason', models.TextField(blank=True, help_text='Reason for blocking (optional)', null=True)),
                ('patient_message_count', models.PositiveIntegerField(default=0, help_text='Number of messages sent by patient')),
                ('donor_message_count', models.PositiveIntegerField(default=0, help_text='Number of messages sent by donor')),
                ('last_message_at', models.DateTimeField(blank=True, help_text='When the last message was sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked_by', models.ForeignKey(blank=True, help_text='User who blocked this conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_conversations', to=settings.AUTH_USER_MODEL)),
                ('blood_request', models.ForeignKey(help_text='The blood request this conversation is about', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='blood_requests.bloodrequest')),
                ('donor', models.ForeignKey(help_text='The donor who pledged to donate', on_delete=django.db.models.deletion.CASCADE, related_name='donor_conversations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='The patient who created the blood request', on_delete=django.db.models.deletion.CASCADE, related_name='patient_conversations', to=settings.AUTH_USER_MODEL)),
                ('pledge', models.OneToOneField(help_text='The pledge that created this conversation', on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='blood_requests.donorresponse')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Message text content', max_length=5000)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('location', 'Location'), ('system', 'System')], default='text', help_text='Type of message', max_length=20)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate for location messages', max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate for location messages', max_digits=9, null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the message has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the message was read', null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether the message was deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When the message was deleted', null=True)),
                ('reported', models.BooleanField(default=False, help_text='Whether the message was reported')),
                ('report_reason', models.TextField(blank=True, help_text='Reason for reporting the message', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(help_text='The conversation this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
                ('sender', models.ForeignKey(help_text='User who sent this message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, help_text='Reason for blocking', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(help_text='User who was blocked', on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(help_text='User who blocked someone', on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blocked User',
                'verbose_name_plural': 'Blocked Users',
                'indexes': [models.Index(fields=['blocker'], name='chat_blocke_blocker_b3c3f8_idx'), models.Index(fields=['blocked'], name='chat_blocke_blocked_24bf56_idx')],
                'unique_together': {('blocker', 'blocked')},
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['patient', 'is_active'], name='chat_conver_patient_676fe6_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['donor', 'is_active'], name='chat_conver_donor_i_dc7490_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-created_at'], name='chat_conver_created_766071_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-updated_at'], name='chat_conver_updated_1f6ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-created_at'], name='chat_messag_convers_d0740f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-created_at'], name='chat_messag_sender__62c9f9_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='chat_messag_is_read_872c73_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['reported'], name='chat_messag_reporte_0de355_idx'),
        ),
    ]
