# Generated by Django 5.2.3 on 2026-06-14 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0012_remove_donorresponse_donated_at_and_more'),
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='pledge',
            field=models.ForeignKey(blank=True, help_text='The most recent pledge that updated this conversation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='blood_requests.donorresponse'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('patient', 'donor')},
        ),
    ]
