# Generated by Django 5.2.3 on 2026-06-14 19:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enable_pledge_updates', models.BooleanField(default=True, help_text='Receive notifications about pledge status changes')),
                ('enable_message_notifications', models.BooleanField(default=True, help_text='Receive notifications for new chat messages')),
                ('enable_request_updates', models.BooleanField(default=True, help_text='Receive notifications about blood request updates')),
                ('enable_promotional', models.BooleanField(default=False, help_text='Receive promotional notifications and updates')),
                ('enable_urgency_alerts', models.BooleanField(default=True, help_text='Receive urgent/SOS notifications')),
                ('enable_push', models.BooleanField(default=True, help_text='Receive push notifications')),
                ('enable_email', models.BooleanField(default=False, help_text='Receive email notifications')),
                ('enable_sms', models.BooleanField(default=False, help_text='Receive SMS notifications')),
                ('quiet_hours_enabled', models.BooleanField(default=False, help_text='Enable quiet hours')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Quiet hours start time', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='Quiet hours end time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User these preferences belong to', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'indexes': [models.Index(fields=['user'], name='notificatio_user_id_0299fd_idx')],
            },
        ),
    ]
