# Generated by Django 5.2.3 on 2026-06-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_add_notification_preferences'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationPreference',
        ),
    ]
