# Generated by Django 5.2.3 on 2026-06-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_delete_notificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, help_text='Additional notification data (donor info, location, etc.)', null=True),
        ),
    ]
