# Generated by Django 5.2.3 on 2026-06-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_otp_attempts_customuser_otp_code_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
