# Generated by Django 5.2.3 on 2026-06-05 19:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_customuser_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Blood type of the user', max_length=5, null=True)),
                ('last_donation_date', models.DateField(blank=True, help_text='Last date of blood donation', null=True)),
                ('total_donations', models.IntegerField(default=0, help_text='Total number of blood donations')),
                ('is_eligible', models.BooleanField(default=True, help_text='Whether user is eligible to donate blood')),
                ('next_eligible_date', models.DateField(blank=True, help_text='Next eligible date for blood donation', null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text="User's date of birth", null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('address', models.TextField(blank=True, help_text='Full address', null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, default='Pakistan', max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True)),
                ('is_available_for_donation', models.BooleanField(default=True, help_text="User's availability for blood donation")),
                ('preferred_donation_time', models.CharField(blank=True, help_text='Preferred time for donation', max_length=50, null=True)),
                ('preferred_donation_location', models.CharField(blank=True, help_text='Preferred donation center/location', max_length=200, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('has_health_conditions', models.BooleanField(default=False, help_text='Whether user has any health conditions')),
                ('health_conditions', models.TextField(blank=True, help_text='Details of health conditions', null=True)),
                ('allergies', models.TextField(blank=True, help_text='Known allergies', null=True)),
                ('medications', models.TextField(blank=True, help_text='Current medications', null=True)),
                ('profile_completed', models.BooleanField(default=False, help_text='Whether user has completed their profile')),
                ('profile_completion_percentage', models.IntegerField(default=0, help_text='Profile completion percentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'indexes': [models.Index(fields=['user'], name='account_use_user_id_cb4799_idx'), models.Index(fields=['blood_type'], name='account_use_blood_t_4384ab_idx'), models.Index(fields=['is_available_for_donation'], name='account_use_is_avai_d66c59_idx'), models.Index(fields=['city', 'state'], name='account_use_city_8ad36d_idx')],
            },
        ),
    ]
