# Generated by Django 5.2.3 on 2026-06-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userprofile'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userprofile',
            name='account_use_blood_t_4384ab_idx',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='blood_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Blood group of the user', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, choices=[('lahore', 'Lahore'), ('islamabad', 'Islamabad'), ('karachi', 'Karachi'), ('multan', 'Multan'), ('quetta', 'Quetta')], help_text='City of residence', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['blood_group'], name='account_use_blood_g_07b44e_idx'),
        ),
    ]
