# Generated by Django 5.2.3 on 2026-06-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_userprofile_account_use_blood_t_4384ab_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userprofile',
            name='account_use_is_avai_d66c59_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='account_use_city_8ad36d_idx',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='has_health_conditions',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='health_conditions',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_available_for_donation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_eligible',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_donation_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='next_eligible_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_donation_location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_donation_time',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_completed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_completion_percentage',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_donations',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture of the user', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['city'], name='account_use_city_afe257_idx'),
        ),
    ]
