# Generated by Django 5.2.3 on 2026-06-06 08:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_userprofile_account_use_is_avai_d66c59_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token for password reset', unique=True, verbose_name='Reset Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Token creation timestamp', verbose_name='Created At')),
                ('is_used', models.BooleanField(default=False, help_text='Whether the token has been used', verbose_name='Used')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Password Reset',
                'verbose_name_plural': 'Password Resets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='account_pas_token_294be6_idx'), models.Index(fields=['user', 'is_used'], name='account_pas_user_id_8e5dd3_idx')],
            },
        ),
    ]
