# Generated by Django 5.2.3 on 2026-06-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_bloodrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodRequest',
        ),
    ]
