# Generated by Django 5.2.3 on 2026-06-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_delete_bloodrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Full address', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, default='Pakistan', help_text='Country', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='eligibility_valid_until',
            field=models.DateField(blank=True, help_text='Date until which eligibility is valid', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='eligibility_verified',
            field=models.BooleanField(default=False, help_text='Whether eligibility has been verified'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_available_for_donation',
            field=models.BooleanField(default=True, help_text='Whether user is available for blood donation'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_donation_date',
            field=models.DateField(blank=True, help_text='Date of last blood donation', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, help_text='State/Province', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_donations',
            field=models.PositiveIntegerField(default=0, help_text='Total number of donations'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, help_text='City of residence', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_available_for_donation'], name='account_use_is_avai_d66c59_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['location_lat', 'location_lng'], name='account_use_locatio_a98e84_idx'),
        ),
    ]
