# Generated by Django 5.2.3 on 2026-06-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_userprofile_address_userprofile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('donor', 'Donor'), ('patient', 'Patient')], help_text='User role: donor or patient', max_length=20, null=True),
        ),
    ]
