# Generated by Django 5.2.3 on 2026-06-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_add_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allergies',
            field=models.JSONField(blank=True, default=list, help_text='List of known allergies'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='eligibility_reason',
            field=models.TextField(blank=True, help_text='Reason if not eligible for donation', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='health_conditions',
            field=models.JSONField(blank=True, default=list, help_text='List of health conditions'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='medications',
            field=models.JSONField(blank=True, default=list, help_text='List of current medications'),
        ),
    ]
