# Generated by Django 5.2.3 on 2026-06-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_userprofile_allergies_userprofile_eligibility_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('donor', 'Donor'), ('patient', 'Patient'), ('admin', 'Admin')], help_text='User role: donor, patient, or admin', max_length=20, null=True),
        ),
    ]
