# Generated by Django 5.2.3 on 2026-06-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cancelled_pledges',
            field=models.PositiveIntegerField(default=0, help_text='Number of pledges cancelled by donor'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_reliable',
            field=models.BooleanField(default=False, help_text='Reliable donor badge (score >= 75)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_top_donor',
            field=models.BooleanField(default=False, help_text='Top donor badge (score >= 90)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified_donor',
            field=models.BooleanField(default=False, help_text='Identity has been verified'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='late_arrivals',
            field=models.PositiveIntegerField(default=0, help_text='Number of times donor arrived late'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='no_shows',
            field=models.PositiveIntegerField(default=0, help_text='Number of no-shows reported'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='on_time_arrivals',
            field=models.PositiveIntegerField(default=0, help_text='Number of times donor arrived on time'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reliability_score',
            field=models.PositiveIntegerField(default=100, help_text='Reliability score (0-100) based on donation history'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='successful_donations',
            field=models.PositiveIntegerField(default=0, help_text='Number of successful donations completed'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_pledges',
            field=models.PositiveIntegerField(default=0, help_text='Total number of pledges made'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-reliability_score'], name='account_use_reliabi_2ef0f3_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_top_donor'], name='account_use_is_top__e33a07_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_reliable'], name='account_use_is_reli_b595c7_idx'),
        ),
    ]
