# Generated by Django 5.2.3 on 2026-06-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_userprofile_cancelled_pledges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, help_text='State/Province', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, default='Pakistan', help_text='Country', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_available_for_donation',
            field=models.BooleanField(default=True, help_text='Whether user is available for blood donation'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_donation_date',
            field=models.DateField(blank=True, help_text='Date of last blood donation', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_donations',
            field=models.PositiveIntegerField(default=0, help_text='Total number of donations'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='eligibility_verified',
            field=models.BooleanField(default=False, help_text='Whether eligibility has been verified'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='eligibility_valid_until',
            field=models.DateField(blank=True, help_text='Date until which eligibility is valid', null=True),
        ),
    ]
