# Generated by Django 5.2.3 on 2026-06-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_remove_userprofile_account_use_is_avai_d66c59_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=9, help_text='Latitude coordinate', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=9, help_text='Longitude coordinate', max_digits=12, null=True),
        ),
    ]
