# Generated by Django 5.2.3 on 2026-06-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_userprofile_location_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=9, help_text='Latitude coordinate (-90 to 90)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=9, help_text='Longitude coordinate (-180 to 180)', max_digits=13, null=True),
        ),
    ]
