# Generated by Django 5.2.3 on 2026-06-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_userprofile_location_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.URLField(blank=True, help_text="URL of the user's profile picture", null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_updated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last profile picture update', null=True),
        ),
    ]
