# Generated by Django 5.2.3 on 2026-06-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, help_text='Full address or location name from location picker', max_length=255, null=True),
        ),
    ]
