# Generated by Django 5.2.3 on 2026-06-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fcm_token',
            field=models.CharField(blank=True, db_index=True, help_text='FCM device token for push notifications', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fcm_token_updated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last FCM token update', null=True),
        ),
    ]
