# Generated by Django 5.2.3 on 2026-06-23 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20260617_1245'),
        ('account', '0023_add_fcm_token_field'),
    ]

    operations = [
    ]
