# Generated by Django 5.2.3 on 2026-06-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_merge_20260623_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='eligibility_valid_until',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='eligibility_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_available_for_donation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_donation_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_donations',
        ),
    ]
