# Generated by Django 5.2.3 on 2026-06-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_remove_userprofile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_available_for_donation',
            field=models.BooleanField(default=True, help_text='Whether the donor is currently available for blood donation'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_donation_date',
            field=models.DateField(blank=True, help_text='Date of last blood donation', null=True),
        ),
    ]
