# Generated by Django 5.2.3 on 2026-06-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_userprofile_is_available_for_donation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='health_quiz_completed',
            field=models.BooleanField(default=False, help_text='Whether the user has completed the health eligibility quiz'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='health_quiz_completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when health quiz was completed', null=True),
        ),
    ]
