# Generated by Django 5.2.3 on 2026-06-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_add_health_quiz_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('donor', 'Donor'), ('patient', 'Patient'), ('admin', 'Admin')], help_text='User role: donor, patient, or admin', max_length=20, null=True),
        ),
    ]
