# Generated by Django 5.2.3 on 2026-06-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_add_role_to_profile'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='account_use_role_417b8d_idx'),
        ),
    ]
