# Generated by Django 5.2.3 on 2026-07-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_userprofile_account_use_role_417b8d_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='availability',
            field=models.JSONField(blank=True, help_text="Donor availability schedule by day and time slots. Format: {'monday': ['8am_10am', '4pm_6pm'], 'tuesday': [...], ...}", null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='available_all_day',
            field=models.BooleanField(default=False, help_text='Whether the donor is available all day, every day'),
        ),
    ]
