# Generated by Django 5.2.3 on 2026-06-06 19:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood_requests', '0001_initial'),
        ('blood_types', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('units', models.PositiveIntegerField(default=1, help_text='Number of units donated')),
                ('donation_date', models.DateField(help_text='Date of donation')),
                ('donation_center', models.CharField(blank=True, help_text='Name of donation center/hospital', max_length=255, null=True)),
                ('donation_center_address', models.TextField(blank=True, help_text='Address of donation center', null=True)),
                ('hemoglobin_level', models.FloatField(blank=True, help_text='Hemoglobin level at time of donation', null=True)),
                ('blood_pressure', models.CharField(blank=True, help_text='Blood pressure reading (e.g., 120/80)', max_length=20, null=True)),
                ('health_status', models.CharField(blank=True, help_text='General health status', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the donation', null=True)),
                ('certificate_issued', models.BooleanField(default=False, help_text='Whether donation certificate has been issued')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_request', models.ForeignKey(blank=True, help_text='Associated blood request (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='blood_requests.bloodrequest')),
                ('blood_type', models.ForeignKey(blank=True, help_text='Blood type donated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='blood_types.bloodtype')),
                ('donor', models.ForeignKey(blank=True, help_text='User who made the donation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-donation_date', '-created_at'],
                'indexes': [models.Index(fields=['donor', '-donation_date'], name='donations_d_donor_i_3cdf18_idx'), models.Index(fields=['blood_request'], name='donations_d_blood_r_b832bc_idx'), models.Index(fields=['donation_date'], name='donations_d_donatio_a63beb_idx')],
            },
        ),
    ]
