# Generated by Django 5.2.3 on 2026-06-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='When patient acknowledged the donation', null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='acknowledged_by_patient',
            field=models.BooleanField(default=False, help_text='Whether patient has acknowledged this donation'),
        ),
        migrations.AddField(
            model_name='donation',
            name='certificate_number',
            field=models.CharField(blank=True, help_text='Unique certificate number', max_length=50, null=True, unique=True),
        ),
    ]
