# Generated by Django 5.2.3 on 2026-06-07 10:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthQuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField(help_text='The question text')),
                ('question_type', models.CharField(choices=[('yes_no', 'Yes/No'), ('multiple_choice', 'Multiple Choice'), ('text', 'Text Input')], default='yes_no', max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='List of options for the question')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the question is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Health Quiz Question',
                'verbose_name_plural': 'Health Quiz Questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HealthQuizResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('responses', models.JSONField(help_text="User's responses as key-value pairs (question_id: answer)")),
                ('is_eligible', models.BooleanField(help_text='Whether user is eligible based on quiz responses', null=True)),
                ('disqualification_reasons', models.JSONField(blank=True, default=list, help_text='List of reasons why user was disqualified')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Quiz Response',
                'verbose_name_plural': 'Health Quiz Responses',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_eligible', models.BooleanField(default=True)),
                ('last_quiz_date', models.DateTimeField(blank=True, null=True)),
                ('disqualification_reasons', models.JSONField(blank=True, default=list)),
                ('eligibility_valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_record', to=settings.AUTH_USER_MODEL)),
                ('last_quiz_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibility_records', to='health.healthquizresponse')),
            ],
            options={
                'verbose_name': 'Eligibility Record',
                'verbose_name_plural': 'Eligibility Records',
            },
        ),
    ]
