web: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --threads 2 --worker-class gthread --worker-timeout 120 --timeout 120
release: python manage.py migrate --noinput && python manage.py collectstatic --noinput
