# Generated by Django 5.2.3 on 2026-06-06 13:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(help_text='Name of the patient requiring blood', max_length=255)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Blood group required', max_length=5)),
                ('units_needed', models.PositiveIntegerField(help_text='Number of blood units required (in pints/bags)')),
                ('urgency_level', models.CharField(choices=[('critical', 'Critical'), ('urgent', 'Urgent'), ('normal', 'Normal')], default='normal', help_text='Urgency level of the blood request', max_length=20)),
                ('contact_number', models.CharField(help_text='Contact number for the requester', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('additional_notes', models.TextField(blank=True, help_text='Additional notes or medical information (optional)', null=True)),
                ('hospital_name', models.CharField(blank=True, help_text='Hospital name where blood is needed (optional)', max_length=255, null=True)),
                ('location', models.CharField(blank=True, help_text='Location/Hospital address (optional)', max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the blood request', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the request is still active/visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, help_text='User who created this blood request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blood Request',
                'verbose_name_plural': 'Blood Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blood_group'], name='blood_reque_blood_g_1b92cc_idx'), models.Index(fields=['urgency_level'], name='blood_reque_urgency_fcf1ff_idx'), models.Index(fields=['status'], name='blood_reque_status_891e77_idx'), models.Index(fields=['is_active'], name='blood_reque_is_acti_cc0a4d_idx'), models.Index(fields=['-created_at'], name='blood_reque_created_feb99c_idx')],
            },
        ),
    ]
