# Generated by Django 5.2.3 on 2026-06-07 09:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='responders_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of donors who pledged'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='units_pledged',
            field=models.PositiveIntegerField(default=0, help_text='Total units pledged by donors'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='units_received',
            field=models.PositiveIntegerField(default=0, help_text='Total units actually donated'),
        ),
        migrations.CreateModel(
            name='DonorResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('units_pledged', models.PositiveIntegerField(default=1, help_text='Number of units pledged')),
                ('preferred_date', models.DateField(blank=True, help_text='Preferred donation date', null=True)),
                ('note', models.TextField(blank=True, help_text='Note from donor to patient', null=True)),
                ('status', models.CharField(choices=[('pledged', 'Pledged'), ('donated', 'Donated'), ('cancelled', 'Cancelled')], default='pledged', help_text='Current status of the pledge', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donated_at', models.DateTimeField(blank=True, help_text='When the donation was completed', null=True)),
                ('blood_request', models.ForeignKey(help_text='The blood request being responded to', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='blood_requests.bloodrequest')),
                ('donor', models.ForeignKey(blank=True, help_text='User who pledged to donate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pledges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donor Pledge',
                'verbose_name_plural': 'Donor Pledges',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blood_request', 'status'], name='blood_reque_blood_r_22f716_idx'), models.Index(fields=['donor', 'status'], name='blood_reque_donor_i_84660b_idx'), models.Index(fields=['-created_at'], name='blood_reque_created_2792f0_idx')],
            },
        ),
    ]
