# Generated by Django 5.2.3 on 2026-06-10 21:00

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0002_bloodrequest_responders_count_and_more'),
        ('account', '0012_add_user_role'),
    ]

    operations = [
        # Update DonorResponse status choices
        migrations.AlterField(
            model_name='donorresponse',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('accepted', 'Accepted'),
                    ('rejected', 'Rejected'),
                    ('donated', 'Donated'),
                    ('cancelled', 'Cancelled'),
                ],
                default='pending',
                help_text='Current status of the pledge',
                max_length=20
            ),
        ),

        # Add new fields to DonorResponse
        migrations.AddField(
            model_name='donorresponse',
            name='units_received',
            field=models.PositiveIntegerField(default=0, help_text='Number of units actually received'),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='accepted_at',
            field=models.DateTimeField(blank=True, help_text='When patient accepted this pledge', null=True),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='When patient rejected this pledge', null=True),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (optional, not shared with donor)', null=True),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='patient_note',
            field=models.TextField(blank=True, help_text='Note from patient to donor', null=True),
        ),

        # Update indexes for DonorResponse
        migrations.AddIndex(
            model_name='donorresponse',
            index=models.Index(fields=['status', 'created_at'], name='blood_reques_status_idx'),
        ),

        # Data migration: Update existing 'pledged' status to 'pending'
        migrations.RunSQL(
            "UPDATE blood_requests_donorresponse SET status = 'pending' WHERE status = 'pledged';",
            reverse_sql="UPDATE blood_requests_donorresponse SET status = 'pledged' WHERE status = 'pending';"
        ),
    ]
