# Generated by Django 5.2.3 on 2026-06-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0010_update_pledge_flow'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='donorresponse',
            new_name='blood_reque_status_9b66b3_idx',
            old_name='blood_reques_status_idx',
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the blood request', max_length=20),
        ),
    ]
