# Generated by Django 5.2.3 on 2026-06-11 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0011_rename_blood_reques_status_idx_blood_reque_status_9b66b3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorresponse',
            name='donated_at',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='active_donor_pledge_id',
            field=models.UUIDField(blank=True, help_text='ID of the currently confirmed (active) donor pledge', null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When this request automatically expires', null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate of request location (patient location)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate of request location (patient location)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='arrived_at',
            field=models.DateTimeField(blank=True, help_text='When donor arrived at the donation location', null=True),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the donation was completed', null=True),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When patient confirmed this pledge as primary donor', null=True),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Donor has verified eligibility before confirmation'),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='no_show_reported_at',
            field=models.DateTimeField(blank=True, help_text='When patient reported donor as no-show', null=True),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='on_the_way_at',
            field=models.DateTimeField(blank=True, help_text="When donor confirmed they're on the way", null=True),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='ready_at',
            field=models.DateTimeField(blank=True, help_text='When donor marked themselves as ready for donation', null=True),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When donor verified eligibility', null=True),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='verified_availability',
            field=models.BooleanField(default=False, help_text='Donor confirmed availability'),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='verified_eligibility',
            field=models.BooleanField(default=False, help_text='Donor confirmed medical eligibility'),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='verified_health_questionnaire',
            field=models.BooleanField(default=False, help_text='Donor completed health questionnaire'),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='verified_last_donation',
            field=models.BooleanField(default=False, help_text='Donor confirmed last donation date'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', help_text='Current status of the blood request', max_length=20),
        ),
        migrations.AlterField(
            model_name='donorresponse',
            name='status',
            field=models.CharField(choices=[('pledged', 'Pledged'), ('shortlisted', 'Shortlisted'), ('confirmed', 'Confirmed'), ('on_the_way', 'On The Way'), ('arrived', 'Arrived'), ('ready', 'Ready for Donation'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('no_show', 'No Show')], default='pledged', help_text='Current status of the pledge', max_length=20),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['location_lat', 'location_lng'], name='blood_reque_locatio_0d4029_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['expires_at'], name='blood_reque_expires_7b7d56_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['-urgency_level', '-created_at'], name='blood_reque_urgency_4dfeab_idx'),
        ),
    ]
