# Generated by Django 5.2.3 on 2026-06-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0012_remove_donorresponse_donated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='broadcast_radius',
            field=models.IntegerField(default=50, help_text='Radius in km for broadcasting the request to nearby donors'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='emergency_donors_notified',
            field=models.IntegerField(default=0, help_text='Number of donors notified for emergency requests'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='emergency_donors_responded',
            field=models.IntegerField(default=0, help_text='Number of donors who responded to emergency requests'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='emergency_expires_at',
            field=models.DateTimeField(blank=True, help_text='When emergency request expires', null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='emergency_first_response_time',
            field=models.DateTimeField(blank=True, help_text='Time of first donor response to emergency', null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='emergency_level',
            field=models.CharField(choices=[('critical', 'Critical'), ('urgent', 'Urgent'), ('normal', 'Normal')], default='normal', help_text='Emergency level for this request', max_length=20),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='is_emergency',
            field=models.BooleanField(default=False, help_text='Whether this is marked as an emergency request'),
        ),
    ]
