# Generated by Django 5.2.3 on 2026-06-23 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0013_bloodrequest_broadcast_radius_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorresponse',
            name='preferred_date',
        ),
    ]
