# Generated by Django 5.2.3 on 2026-06-23 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0014_remove_preferred_date_from_donor_response'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='share_id',
            field=models.CharField(blank=True, db_index=True, help_text='Short shareable ID for external sharing (e.g., abc123xy)', max_length=12, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['share_id'], name='blood_reque_share_i_2dd980_idx'),
        ),
    ]
