# Generated by Django 5.2.3 on 2026-06-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0015_bloodrequest_share_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='quiz_responses',
            field=models.JSONField(blank=True, help_text="Patient's quiz responses as JSON data", null=True),
        ),
    ]
