# Generated by Django 5.2.3 on 2026-06-24 09:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0016_add_quiz_responses'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientQuiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('had_blood_transfusion', models.BooleanField(default=False, help_text='Had blood transfusion in last 3 months')),
                ('had_tattoo_piercing', models.BooleanField(default=False, help_text='Had tattoos or piercings in last 6 months')),
                ('had_surgery', models.BooleanField(default=False, help_text='Had major surgery in last 6 months')),
                ('on_medication', models.BooleanField(default=False, help_text='Currently on medication')),
                ('has_chronic_disease', models.BooleanField(default=False, help_text='Has chronic diseases')),
                ('traveled_malaria_area', models.BooleanField(default=False, help_text='Traveled to malaria-prone areas in last 12 months')),
                ('other_medical_info', models.TextField(blank=True, help_text='Additional medical information provided by patient', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_request', models.OneToOneField(help_text='Associated blood request', on_delete=django.db.models.deletion.CASCADE, related_name='patient_quiz', to='blood_requests.bloodrequest')),
            ],
            options={
                'verbose_name': 'Patient Quiz',
                'verbose_name_plural': 'Patient Quizzes',
                'ordering': ['-created_at'],
            },
        ),
    ]
