# Generated by Django 5.2.3 on 2026-06-28 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0017_patientquiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientQuiz',
        ),
    ]
