# Generated by Django 5.2.3 on 2026-06-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0018_remove_patient_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='needed_by',
            field=models.DateTimeField(blank=True, help_text='Date and time when blood is needed by', null=True),
        ),
    ]
