# Generated by Django 5.2.3 on 2026-06-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0020_make_needed_by_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorresponse',
            name='donor_address',
            field=models.TextField(blank=True, help_text='Address of external donor', null=True),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='donor_blood_group',
            field=models.CharField(blank=True, help_text='Blood group of external donor', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='donor_city',
            field=models.CharField(blank=True, help_text='City of external donor', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='donor_location_lat',
            field=models.DecimalField(blank=True, decimal_places=7, help_text="Latitude of external donor's location", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='donor_location_lng',
            field=models.DecimalField(blank=True, decimal_places=7, help_text="Longitude of external donor's location", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='donor_name',
            field=models.CharField(blank=True, help_text='Name of external donor (no account)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='donor_phone',
            field=models.CharField(blank=True, help_text='Phone number of external donor', max_length=20, null=True),
        ),
    ]
