
"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config, config as env
import dotenv
import os

# Use PyMySQL as MySQL client (pure Python - no compilation)
import pymysql
pymysql.install_as_MySQLdb()

# Load environment variables from .env file
dotenv.load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l1-&ii&8$6@+01l842gzi9d)87h5dc(o95a0rz+&ujhieh51a='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Allow all hosts for development (update for production)
# For ngrok, specifically add: '6411-103-150-239-29.ngrok-free.app'

# External Pledge System: Public base URL for share links
# Configure this to your production domain (e.g., 'https://bloodconnect.com')
# For local testing: 'http://localhost:8000'
# For ngrok (mobile testing): 'https://6411-103-150-239-29.ngrok-free.app'
PUBLIC_BASE_URL = os.environ.get('PUBLIC_BASE_URL', 'http://localhost:8000')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',
    'account',
    'blood_requests',
    'blood_types',
    'donations',
    'sos',
    'stats',
    'health',
    'notifications',  # Push notifications via FCM
    # Phase 0: Production Infrastructure
    'channels',  # WebSocket support
    # Phase 8: Chat System
    'chat',  # Private messaging between patients and donors
    # AI Chatbot Assistant
    'assistant',  # AI-powered FAQ chatbot
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'blood_requests' / 'templates'],  # External pledge system templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SQLite Configuration (for testing)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# MySQL Configuration (for production)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'blood_donation_db',
        'USER': 'root',
        'PASSWORD': 'password',  # Add your MySQL password here
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'account.CustomUser'

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
}

# JWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

# CORS Configuration for Flutter App
CORS_ALLOW_CREDENTIALS = True

# Allow all origins for development (CHANGE IN PRODUCTION!)
CORS_ALLOW_ALL_ORIGINS = True

# REST Framework Pagination
REST_FRAMEWORK['DEFAULT_PAGINATION_CLASS'] = 'rest_framework.pagination.PageNumberPagination'
REST_FRAMEWORK['PAGE_SIZE'] = 20

# Security Settings for Production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# SMS Service Configuration
SMS_PROVIDER = 'development'  # Options: 'twilio', 'firebase', 'development'

# Twilio Configuration (for production)
TWILIO_ACCOUNT_SID = env('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = env('TWILIO_AUTH_TOKEN', default='')
TWILIO_PHONE_NUMBER = env('TWILIO_PHONE_NUMBER', default='')

# Firebase Configuration (optional)
_firebase_path = env('FIREBASE_CREDENTIALS_PATH', default='')
FIREBASE_CREDENTIALS_PATH = str(BASE_DIR / _firebase_path) if _firebase_path and not _firebase_path.startswith('/') else _firebase_path

# Firebase Admin SDK Configuration for Push Notifications
# Path to Firebase service account JSON file
FIREBASE_CREDENTIALS = env('FIREBASE_CREDENTIALS', default=None)

# SOS Notification Settings
SOS_NOTIFICATION_RADIUS_KM = env('SOS_NOTIFICATION_RADIUS_KM', default=50, cast=int)


# Email Configuration
EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = env('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='')
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# For development, you can use console backend to see emails in console
# Uncomment the line below to use console backend instead of SMTP
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Frontend URL for password reset links
FRONTEND_URL = env('FRONTEND_URL', default='http://localhost:3000')

# App deep link scheme for mobile app
APP_DEEP_LINK_SCHEME = env('APP_DEEP_LINK_SCHEME', default='blooddonation')


# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} [{module}] {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'account': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# Create logs directory if it doesn't exist
import os
os.makedirs(BASE_DIR / 'logs', exist_ok=True)


# ===============================
# PHASE 0: PRODUCTION INFRASTRUCTURE
# ===============================

# ASGI application for Django Channels
ASGI_APPLICATION = 'backend.asgi.application'

# Channel layers using InMemory (no Redis required)
# Suitable for development and single-server deployments
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# ===============================
# LLM Configuration for AI Chatbot
# ===============================

# Enable/disable LLM service (fallback to TF-IDF if disabled)
LLM_ENABLED = os.environ.get('LLM_ENABLED', 'true').lower() != 'false'

# OpenRouter API configuration
OPENROUTER_API_KEY = os.environ.get('OPENROUTER_API_KEY')
OPENROUTER_MODEL = os.environ.get('OPENROUTER_MODEL', 'openrouter/free')
LLM_TEMPERATURE = os.environ.get('LLM_TEMPERATURE', '0.7')
LLM_MAX_TOKENS = os.environ.get('LLM_MAX_TOKENS', '500')

# ===============================
# Firebase Initialization
# ===============================

# Initialize Firebase Admin SDK for FCM
try:
    from firebase_admin import credentials, initialize_app
    import firebase_admin

    # Check if already initialized
    if not firebase_admin._apps:
        # Get Firebase credentials path
        firebase_credentials_path = os.environ.get('FIREBASE_CREDENTIALS_PATH')

        # Resolve relative path to absolute path
        if firebase_credentials_path and not firebase_credentials_path.startswith('/'):
            firebase_credentials_path = str(BASE_DIR / firebase_credentials_path)

        print(f"Looking for Firebase credentials at: {firebase_credentials_path}")

        if firebase_credentials_path and os.path.exists(firebase_credentials_path):
            cred = credentials.Certificate(firebase_credentials_path)
            firebase_project_id = os.environ.get('FIREBASE_PROJECT_ID', 'blood-donation-chat')
            initialize_app(cred, options={'project_id': firebase_project_id})
            print("SUCCESS: Firebase Admin SDK initialized successfully")
        else:
            print("WARNING: Firebase credentials not found - FCM notifications will not work")
except Exception as e:
    print(f"ERROR: Failed to initialize Firebase: {e}")
